### ISSUE TITLE
Stockholm - Avrådan från bad

### ISSUE THREAD

**Issue by salgo60** [salgo60/Svenskabadplatser#118]
Intressant case med [avrådan som uppstår ](https://twitter.com/Stockholmsstad/status/1398207309357146116?s=20) vad kan göras bättre? 
* provsvar vecka 22 [länk Hav](https://www.havochvatten.se/badplatser-och-badvatten/kommuner-och-badplatser/kommuner/badplatser-i-stockholms-kommun.html)
* allt hittills jag ser är bara på svenska

![image](https://user-images.githubusercontent.com/14206509/120068102-4f5ff380-c07f-11eb-8119-7b63da4b37a8.png)

![image](https://user-images.githubusercontent.com/14206509/120053599-5230f900-c02b-11eb-8fc5-650a07da3ab5.png)

Är inte detta ett bra exempel på att man skall stödja design mönstret [SSoT](https://en.wikipedia.org/wiki/Single_source_of_truth) se https://github.com/salgo60/Svenskabadplatser/discussions/113 dvs. 
* vi har ett ställe där vi kan lita på datat? Får en [känsla att man inte på Stockholms stad](https://www.havochvatten.se/badplatser-och-badvatten/kommuner-och-badplatser/kommuner/badplatser-i-stockholms-kommun.html) enkelt kan generera kartor var dessa bad ligger dvs. man jobbar inte data drivet utan det är statiska websidor som uppdateras för hand även [Hav känns fel designat](https://badplatsen.havochvatten.se/badplatsen/karta/#/) med deras karta som inte visar var bad med problem finns utan man måste klicka in sig på alla bad - hade kartdesignern följt SSoT så hade den kollat **dissuasion/type** för om detta är ett bad att visa :weary:
* lite udda att Stockholms stad pekar på Havs- och vattenmyndigheten och Havs- och vattenmyndigheten pekar tillbaka att det är kommunen som skall ta beslutet 

* se 
  * [Avrådan från bad](https://start.stockholm/aktuellt/nyheter/2021/05/avradan-fran-bad/) - start.stockholm  
     * Lista "[Badplatser och kvalitet på badvatten i Stockholms kommun](https://www.havochvatten.se/badplatser-och-badvatten/kommuner-och-badplatser/kommuner/badplatser-i-stockholms-kommun.html)"
       * intressant är att nedre delen av den sidan under **Alla badplatser** visar inte avrådan gissar att man inte jobbar datadrive eller inte funderat över "avrådan" user case... 
     * [SE011018000000185](https://badplatsen.havochvatten.se/badplatsen/karta/#/bath/SE0110180000001850) 
  * [DN](https://www.dn.se/sthlm/stockholm-avrader-fran-bad-efter-skyfallet/) 
  
**Mina tankar**
 1) [SSoT](https://en.wikipedia.org/wiki/Single_source_of_truth) är viktigt att vara **tydlig** med att 
     1) denna datamängd finns och är [SSoT](https://en.wikipedia.org/wiki/Single_source_of_truth) 
     1) skall vi kolla trovärdigheten på information så stäm av med denna källa
     1) för varningar och att se till att detta datat är korrekt 
 1) json som skapas hos  Hav har inga språktaggar skall bara svenskspråkiga informeras? Finns en **dissuasion/type 4** som borde i en bra design kunna kopplas till ett objekt som kan visas på flera språk
     1) i [Badplatsen publikt API](https://drive.google.com/file/d/1vjv9B5a4gLU2k5jXCjXoB9_2Xwy1mDfU/view) verkar inte ha tagits höjd för språk trots att datat skall skickas till EU -> **GöromGörRätt**
 1) _dissuasion_ har startDatum men inget stopDatum i specen
 1) _dissuasion_ verkar vara en lokal term hittar den inte i [dd.eionet.europa.eu](https://dd.eionet.europa.eu/searchelements?filter.defaultAttributes%5B2%5D.name=Keywords&filter.defaultAttributes%5B1%5D.id=4&__fp=uuNLCrCmovyfHf1SCEwl6FSz34DYywFLGPC0zxz5qeo9Nc5OFx_4ZjPAiY5zmo8fF_3eqXT3Wr5FM2GshlR2UZAiHodTWGYKheYTtEezxDeBSTzY9CWZMWZ6t5X1DALP-BUi1l4TWq2OFmM5WW5hvw%3D%3D&filter.defaultAttributes%5B2%5D.id=5&sort=IDENTIFIER&dir=asc&filter.defaultAttributes%5B2%5D.shortName=Keyword&filter.defaultAttributes%5B0%5D.shortName=Name&filter.defaultAttributes%5B0%5D.value=&filter.defaultAttributes%5B0%5D.id=1&filter.type=&filter.defaultAttributes%5B1%5D.value=&filter.elementType=nonCommon&search=Search&addAttr=0&_sourcePage=kyFPFvJi8plK7uPz_vre6_WCua3V2e3CskwZJFq5lkzdCHtoiHu1EQ%3D%3D&filter.pageSize=1000&filter.shortName=&filter.defaultAttributes%5B0%5D.name=Name&filter.defaultAttributes%5B1%5D.name=Definition&filter.defaultAttributes%5B2%5D.value=&filter.defaultAttributes%5B1%5D.shortName=Definition&filter.dataSet=&filter.identifier=)

![image](https://user-images.githubusercontent.com/14206509/120052081-c8c9f880-c023-11eb-9980-27a58989567e.png)
 
![image](https://user-images.githubusercontent.com/14206509/120052107-e7c88a80-c023-11eb-8a22-f151614f10bf.png)

* avrådan verkar inte visas på Hav snygga karta men i detta fall ej funktionella  

![image](https://user-images.githubusercontent.com/14206509/120052235-88b74580-c024-11eb-8baa-2abe2bd88293.png)

* avrådan visas endast om man klickar badet ex. [SE011018000000185](https://badplatsen.havochvatten.se/badplatsen/karta/#/bath/SE0110180000001850) 
  * API detail [SE0110180000001850](https://badplatsen.havochvatten.se/badplatsen/api/detail/SE0110180000001850)
  * datat har strings utan språkkod - _oldschool_ 
```
  <dissuasions>
     <dissuasion> 
          <startdate>2021-05-27T16:04:58+02:00</startdate>
          <description>På grund av intensivt regnande har inte allt vatten i stadens avlopp kunnat renas. Badvattnet kan därför vara otjänligt. Provsvar beräknas komma i slutet av vecka 22.</description>
          <type>4</type>
         <dissuasionTypeText>Oväntad situation</dissuasionTypeText>
     </dissuasion>
</dissuasions>
```
![image](https://user-images.githubusercontent.com/14206509/120053240-7390e580-c029-11eb-90ba-a3f27a20e051.png)
![image](https://user-images.githubusercontent.com/14206509/120053266-8acfd300-c029-11eb-8d4c-31f5aa711abd.png)

  * API testlocationprofile [SE0110180000001850](https://badplatsen.havochvatten.se/badplatsen/api/testlocationprofile/SE0110180000001850)
      * innehåller vad som gjorts och vad som bör göras men som textsträngar borde kunna kopplas till ärenden i andra system eller beslut av kommunen

![image](https://user-images.githubusercontent.com/14206509/120051965-388bb380-c023-11eb-9de1-7e7bb58ff362.png)

cc: @TGBMonsen

**Comment by dpriskorn** [comment]
Textsträng utan språkangivning är skräp. Det är en allvarlig brist tycker jag.

**Comment by salgo60** [comment]
Japp galet när man vet att man skall rapporterar till EU skall prata med dom på måndag tror nytt API är på G

**Comment by salgo60** [comment]
Wikidata karta för baden med avrådan för bad

* [karta](https://query.wikidata.org/embed.html#%23defaultView%3AMap%0ASELECT%20DISTINCT%20%3Fbathwaterissues%20%3Fnode%20%3FnodeLabel%20%20%3Fcoord%20WHERE%20%7B%0A%20%20%20VALUES%20%3Fbathwaterissues%20%7B%20%22SE0110180000001831%22%20%22SE0110180000001832%22%20%22SE0110180000001834%22%20%22SE0110180000001836%22%20%22SE0110180000001837%22%0A%20%20%20%20%20%20%20%20%20%22SE0110180000001838%22%20%22SE0110180000001839%22%20%22SE0110180000001840%22%20%22SE0110180000001841%22%20%22SE0110180000001842%22%20%22SE0110180000001843%22%0A%20%20%20%20%20%20%20%20%20%22SE0110180000001845%22%20%22SE0110180000001846%22%20%22SE0110180000001847%22%20%22SE0110180000001848%22%20%22SE0110180000001849%22%20%22SE0110180000001850%22%0A%20%20%20%20%20%20%20%20%20%20%22SE0110180000001851%22%20%22SE0110180000001863%22%20%22SE0110180000001864%22%20%22SE0110180000001866%22%20%22SE0110180000001867%22%20%22SE0110180000001868%22%20%0A%20%20%20%20%20%20%20%20%20%20%22SE0110180000001869%22%20%22SE0110180000001870%22%20%22SE0110180000001871%22%20%20%22SE0110180000001872%22%20%22SE0110180000003634%22%20%22SE0110180000004020%22%20%0A%20%20%20%20%20%20%20%20%20%20%22SE0110180000004021%22%20%22SE0110180000004188%22%20%22SE0110180000004456%22%20%22SE0110180000004457%22%20%22SE0110180000004458%22%20%22SE0110180000004459%22%0A%20%20%20%20%20%20%20%20%20%20%22SE0110180000004489%22%20%22SE0110180000004555%22%7D%0A%20%20%20%3Fnode%20wdt%3AP605%20%3Fbathwaterissues.%0A%20%20%20%23%3Fnode%20wdt%3AP131%20%3Fadmin.%0A%20%20%20%3Fnode%20wdt%3AP625%20%3Fcoord.%0A%20%20%0A%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22sv%2Cen%22.%20%7D%0A%7D) / [SPARQL](https://query.wikidata.org/#%23defaultView%3AMap%0ASELECT%20DISTINCT%20%3Fbathwaterissues%20%3Fnode%20%3FnodeLabel%20%20%3Fcoord%20WHERE%20%7B%0A%20%20%20VALUES%20%3Fbathwaterissues%20%7B%20%22SE0110180000001831%22%20%22SE0110180000001832%22%20%22SE0110180000001834%22%20%22SE0110180000001836%22%20%22SE0110180000001837%22%0A%20%20%20%20%20%20%20%20%20%22SE0110180000001838%22%20%22SE0110180000001839%22%20%22SE0110180000001840%22%20%22SE0110180000001841%22%20%22SE0110180000001842%22%20%22SE0110180000001843%22%0A%20%20%20%20%20%20%20%20%20%22SE0110180000001845%22%20%22SE0110180000001846%22%20%22SE0110180000001847%22%20%22SE0110180000001848%22%20%22SE0110180000001849%22%20%22SE0110180000001850%22%0A%20%20%20%20%20%20%20%20%20%20%22SE0110180000001851%22%20%22SE0110180000001863%22%20%22SE0110180000001864%22%20%22SE0110180000001866%22%20%22SE0110180000001867%22%20%22SE0110180000001868%22%20%0A%20%20%20%20%20%20%20%20%20%20%22SE0110180000001869%22%20%22SE0110180000001870%22%20%22SE0110180000001871%22%20%20%22SE0110180000001872%22%20%22SE0110180000003634%22%20%22SE0110180000004020%22%20%0A%20%20%20%20%20%20%20%20%20%20%22SE0110180000004021%22%20%22SE0110180000004188%22%20%22SE0110180000004456%22%20%22SE0110180000004457%22%20%22SE0110180000004458%22%20%22SE0110180000004459%22%0A%20%20%20%20%20%20%20%20%20%20%22SE0110180000004489%22%20%22SE0110180000004555%22%7D%0A%20%20%20%3Fnode%20wdt%3AP605%20%3Fbathwaterissues.%0A%20%20%20%23%3Fnode%20wdt%3AP131%20%3Fadmin.%0A%20%20%20%3Fnode%20wdt%3AP625%20%3Fcoord.%0A%20%20%0A%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22sv%2Cen%22.%20%7D%0A%7D)
![image](https://user-images.githubusercontent.com/14206509/120063766-22a0e180-c069-11eb-9983-2c356b368345.png)

Handjagad lista av bad
* SE0110180000001831 SE0110180000001832 SE0110180000001834 SE0110180000001836 SE0110180000001837 SE0110180000001838 SE0110180000001839 SE0110180000001840 SE0110180000001841 SE0110180000001842 SE0110180000001843 SE0110180000001845 SE0110180000001846 SE0110180000001847 SE0110180000001848 SE0110180000001849 SE0110180000001850 SE0110180000001851 SE0110180000001863 SE0110180000001864 SE0110180000001866 SE0110180000001867 SE0110180000001868 SE0110180000001869 SE0110180000001870 SE0110180000001871  SE0110180000001872 SE0110180000003634 SE0110180000004020 SE0110180000004021 SE0110180000004188 SE0110180000004456 SE0110180000004457 SE0110180000004458 SE0110180000004459 SE0110180000004489 SE0110180000004555

**Comment by salgo60** [comment]
cc: Stockholmsstad en karta på [twitter](https://twitter.com/Stockholmsstad/status/1398207309357146116?s=20)

![image](https://user-images.githubusercontent.com/14206509/120067220-b4651a80-c07a-11eb-9052-25552b0b6bf1.png)

**Comment by salgo60** [comment]
![image](https://user-images.githubusercontent.com/14206509/120078011-982ea100-c0ad-11eb-9a9f-6d7db596d341.png)

**Comment by salgo60** [comment]
cc: @TGBMonsen 
hade långt prat med [Mattias på Hav](https://github.com/salgo60/Svenskabadplatser#kontakter) och 
1) Stockholms kommun hade gått in på Hav och uppdaterad avrådan
  1) Han tycker det är ett enormt bra mönster att kommuner har sina bad hos Hav
      1) att avrådan uppdateras på detta ställe
      1) att när provsvar dyker upp så uppdateras detta ställe
      1) att kommunerna även pekar på denna databas
      1) jag framförde att vi gärna ser att ytor för baden finns i GeoJson med CC-0 så vi kan ha dom i Wikidata
   1) Lät som det finns ett Hav projekt om hur kommunerna skall uppdatera detta data - men frågade inget mera
 1) vi pratade även [bathingWaterIdentifier](https://www.wikidata.org/wiki/Wikidata:Property_proposal/bathingWaterIdentifier) men där kunde han inte säga mer verkar som det är flera avdelningar som jobbar med badvatten så jag gissar att den blir kvar i API:et, han var även osäker på om EUbad som rapporteras till EU har en [bathingWaterIdentifier](https://www.wikidata.org/wiki/Wikidata:Property_proposal/bathingWaterIdentifier) som är registrerad i "WFDProtectedArea" vilket det skall vara enligt [dd.eionet.europa.eu/dataelements/99263](https://dd.eionet.europa.eu/dataelements/99263)

**Comment by soleildeminuit** [comment]
Ok, bra. Tack för att du tog kontakten! HaV måste dock samordna och styra geodata, dvs hur badplatsernas geografiska positioner och adresser. Förutom låg kvalitet i koordinatangivelser (p.g.a manuell inmatning?), så finns även brister i API:et och specifikationerna. HaV följer inte nationell kartinformation för blåljusaktörer. MSB har kartor för krisberedskap och blåljus och det är viktigt att alla specar för badplatser följer dessa nationella riktlinjer. Det är vanligt att ambulans och räddningstjänst rycker ut till badplatser och felaktiga koordinater eller en spec. som inte kan användas i blåsljusverksamhetens fordonsnavigatorer, kan få katastrofala konsekvenser. Jag ser idag att många specar endast använder WGS84, det är inte i linje med MSB:s riktlinjer (som säger att det svenska nationella referenssystemet ska användas). Kommunerna har inte heller alltid verksamhetssystem som hanterar WGS84, GIS-plattformarna arbetar med de kommunala, lokala, systemen, som inte lämpar sig för extern användning. Att tvinga WGS84 leder till manuell transformation och manuellt klickande på webbkartor.

**Comment by TGBMonsen** [comment]
Mot bakgrund av detta framkomna undrar jag, för att kunna färdigställa min specifikation med högsta, just nu, uppnåbara kvalite:

- Kan jag beholla "nutscode" som attribut för att referera till API hos Hav, eller ska jag byta namn på det attributet, isåfall till vad?
- Ska jag lägga till SWEREF99 -koordinatsystem förutom WGS84 och göra endera av dessa obligatoriska eller bara den ena, isåfall vilken?

**Comment by soleildeminuit** [comment]
Enklast är att du kollar med din kommun om hur ni ligger till i arbetet med [Blåljuskollen](https://www.lantmateriet.se/sv/Om-Lantmateriet/Samverkan-med-andra/geodata-for-blaljus/blaljuskollen/) . Det finns även nationell hjälp att få för kommunerna, MSB och Lantmäteriet har tagit fram checklistor, t.ex. [MSB](https://krisberedskapskartor.msb.se/verktyg-och-tjanster)
MSB skriver: "Ett gemensamt koordinatsystem utgör en av grunderna för att blåljusaktörer ska kunna kommunicera om positionen för en händelse." SWEREF99 TM är det nationella, rikstäckande koordinatsystemet (observera "TM" i beteckningen!), WGS84 är däremot det som vanligen används i "konsumentsammanhang", så båda är nödvändiga.

**Comment by salgo60** [comment]
1) "nutscode" jag skulle säga att Mattias var fel person att prata med.... orkar du leta reda på andra personer
1) jag slänger över allt deras till **Eionet bathingWaterIdentifier** just nu (min [change log](https://www.wikidata.org/w/index.php?title=Special:Contributions/Salgo60&offset=&limit=500&target=Salgo60))  jag fick just denna egenskap i Wikidata godkänt [Property:P9616](https://www.wikidata.org/wiki/Property:P9616) så jag skickar över allt dit och tar bort Nuts på alla badplatser --> alla SPARQL skapade hittills dör så skrik till ;-) 

Det jag skulle vilja se hos Hav är det man ser hos Wikidata se exempel [Signed Statements](https://community.dataportal.se/topic/117/digisam-har-en-ny-v%C3%A4gledning-f%C3%B6r-ett-sammanl%C3%A4nkat-kulturarv/2?_=1622555773636)
* tydliga roadmaps där man kan se vad som finns
* öppen backlog som kan diskuteras 

mitt snack med Mattias var mer informellt och ad hoc .... gissar att dom inte är mogna att ha öppna prioriterade backlogs

**Comment by soleildeminuit** [comment]
1. "nutscode", jag skulle säga att det är "nuts" att använda den ;) Allvarligt talat, sprider bara förvirring.
2. Bra!
(3.) Ang. koordinaterna om/när du lägger till nationella referenssystemet, då behövs en tydlig instruktion om att de två systemens koordinatangivelser måste dels stämma med platsen (givetvis), men även stämma med varandra och - om du lägger till adress så behöver även den vara avstämd med resp. kommun/lantmäterimyndighet.

**Comment by salgo60** [comment]
Verkar som Wikidata vill att jag skall plugga ML eller ut och cykla ;-)

Har ändrat för mycket sista tiden

![image](https://user-images.githubusercontent.com/14206509/120338632-b6d2a900-c2f4-11eb-8035-4742070f0816.png)

**Comment by soleildeminuit** [comment]
Ser att ÖDIS (Stockholms stad) skrivit rekommendationer om koordinatsystem, virrigt (och delvis felaktigt), men ändå ett försök att göra rätt.
![image](https://user-images.githubusercontent.com/10654578/120377756-d631fc00-c31d-11eb-91ee-415146f49e64.png)

Som sagt, ett tips kan vara att börja med att titta på ÖDIS och sen är det bara att posta ev. frågor här på GitHub-ytan.

Det här är inte så krångligt som det verkar, men det är väldigt viktigt att det blir rätt.

**Comment by salgo60** [comment]
2 bad i Stockholm verkar vara avstängda resten av året
* [SE0110180000001849](https://badplatsen.havochvatten.se/badplatsen/karta/#/bath/SE0110180000001849)
* [SE0110180000001841](https://badplatsen.havochvatten.se/badplatsen/karta/#/bath/SE0110180000001841)

![image](https://user-images.githubusercontent.com/14206509/121585855-58fc3a80-ca33-11eb-9bf0-db96bd38de2f.png)

**Comment by salgo60** [comment]
Nu verkar Stockholms stad ha skyltar med QRC koder till sidan om badplatser Stockholms stad hos Havs myndigheten

* [länk som QRCkoden går till](https://www.havochvatten.se/badplatser-och-badvatten/kommuner/badplatser-i-stockholms-kommun.html)

![image](https://github.com/user-attachments/assets/7df05338-c08b-4680-9af2-21671f19f4fc)

![image](https://github.com/user-attachments/assets/c65a6c84-99b4-4358-92e9-a36f6fb18e35)

![image](https://github.com/user-attachments/assets/65ab0e59-9707-45e5-9f61-69f17aace72f)

![image](https://github.com/user-attachments/assets/3183324f-1dd1-413b-ab14-bcfbe2fbd845)

**Comment by salgo60** [comment]
[Önskar ha motsvarande QRC koder för alla fysiska objekt som kan felanmälas](https://github.com/dpriskorn/svenska-grillplatser/issues/55)

**Comment by salgo60** [comment]
* Havsmyndigheten borde stödja fler språk en svenska särskilt för badförbud

Kollar vi på APIet så känns allt som textsträngar och inget länkade data

**Comment by salgo60** [comment]
### Status 2026

Känns inte som vi rör oss framåt [Verva NSÖD DIGG](https://github.com/salgo60/DIGG-skuggbacklog/issues/1474)... alla i graven. Varken tid eller pengar gör skillnad....

<img width="2620" height="1290" alt="Image" src="https://github.com/user-attachments/assets/09be0bb2-7e46-40e0-a423-5e178e9bdecb" />
