### ISSUE TITLE
Mörtsjöbadet, Stugun vart ligger det?

### ISSUE THREAD

**Issue by dpriskorn** [salgo60/Svenskabadplatser#175]
![image](https://github.com/salgo60/Svenskabadplatser/assets/68460690/e447a8e5-62ef-4c91-8084-acc1c2c8cf88)
Hej!

Läser
https://www.ltz.se/2021-06-18/mortsjobadet--en-naturskon-plats

Tyvärr har jag ingen aning om var den ligger. Hittar inte på goggle
eller när jag söker.

Har nån av er koordinater till den?

**Comment by dpriskorn** [comment]
se https://www.wikidata.org/wiki/Q121359046

**Comment by salgo60** [comment]
Duger inte

'''Mörtsjöbadet ligger mellan Östra och Västra Mörtsjön, cirka 8 km från centrala Stugun. Man kör österut efter väg 87 och svänger av till vänster vid skylten mot Mörtsjön.'''

**Comment by dpriskorn** [comment]
upphittat via naturkartan
