### ISSUE TITLE
Diff Swedish bath waters between API  badplatsen.havochvatten.se/badplatsen/api 2686 and uploaded bath waters 438 

### ISSUE THREAD

**Issue by salgo60** [salgo60/Svenskabadplatser#18]
We find **439 Swedish bathing** waters in https://discomap.eea.europa.eu/Bathingwater/

![image](https://user-images.githubusercontent.com/14206509/118190672-c2dcf080-b443-11eb-9116-a9591b5d9823.png)

In API [badplatsen/api/feature](https://badplatsen.havochvatten.se/badplatsen/api/feature) we have **2686** and in Wikidata we have [additional some in this projects](https://w.wiki/3KP5) > 2700

![image](https://user-images.githubusercontent.com/14206509/118255305-6366fb00-b4ac-11eb-9c96-bb23e020b543.png)

* see also [notebook](https://github.com/salgo60/Svenskabadplatser/blob/main/Jupyter/BathWater.ipynb) - Sweden is SE
![image](https://user-images.githubusercontent.com/14206509/118255407-842f5080-b4ac-11eb-9c0d-8c565331d537.png)

**Comment by anderselias** [comment]
The badplatsen/api/feature API has an attribute **euType** (a boolean flag) that, according to the docs, indicates whether the site is to reported to EU or not (in Swedish "Flagga som anger om badet är ett EU bad eller ej")

> table(testLocations$euType)

FALSE  TRUE 
 2155   440

**Comment by salgo60** [comment]
Then the question is 
* do we have Nutskod for 2155
* do we have bathingWaterIdentifier for just 440 or 2155

I guess https://dd.eionet.europa.eu/dataelements/99263 states that _"Must be a valid bathing water identifier in the "WFDProtectedArea" registry"_

**Comment by anderselias** [comment]
I agree, best to stick to established nomenclature...We do have **nutsCode** for all of them, but the term **bathingWaterIdentifier** does not exist in the API. There are more test locations/sites then what I mentioned, the import fails for a couple of dozens, probably due to data quality issues.

**Comment by anderselias** [comment]
Not all of the **nutsCode** has an associated test location profile, for example:
https://badplatsen.havochvatten.se/badplatsen/api/testlocationprofile/SE0930861000004814

**Comment by salgo60** [comment]
Do we have a good specification of the NUTScode?

In Wikidata we call it [Property:P605](https://www.wikidata.org/wiki/Property:P605) and have a regexp **[A-Z]{2}[A-Z0-9]{0,3}**
![image](https://user-images.githubusercontent.com/14206509/118357329-e73ae900-b579-11eb-9d6f-d710a26bd86d.png)

and a formatter URL http://dd.eionet.europa.eu/vocabularyconcept/common/nuts/$1
==>
* Sweden -> list what we have in [WD for Sweden](https://w.wiki/3L53) 
* bath water NUTScode -> dont follow this pattern and is not in the db e.g. 
  * SE0241884000004954 http://dd.eionet.europa.eu/vocabularyconcept/common/nuts/SE0241884000004954 same as WD [Q106712205](https://www.wikidata.org/wiki/Q106712205) 
  * SE0110136000002142  http://dd.eionet.europa.eu/vocabularyconcept/common/nuts/SE0110136000002142 same as WD [Q49099077](https://www.wikidata.org/wiki/Q49099077)

**Comment by salgo60** [comment]
@anderselias 
SE0930861000004814 see https://github.com/salgo60/Svenskabadplatser/issues/33
* do you have a list of them I guess al of them are errors in Wikidata...
