### ISSUE TITLE
SE0930861000004814 saknar koordinat - Gamla färjeläget Oknö

### ISSUE THREAD

**Issue by salgo60** [salgo60/Svenskabadplatser#33]
SE0930861000004814
* WD [Q106712174](https://www.wikidata.org/wiki/Q106712174)
* [API](https://badplatsen.havochvatten.se/badplatsen/api/feature) 

![image](https://user-images.githubusercontent.com/14206509/118358581-c2497480-b57f-11eb-9527-aa07c472bfb0.png)

**Comment by anderselias** [comment]
[1] "SE0930861000004814 missing test location"
[1] "SE0110191000004834 missing test location"
[1] "SE0241884000004954 missing test location"

**Comment by salgo60** [comment]
Found link in [DIgitaltmuseum](https://digitaltmuseum.se/021017081910) [57.0005, 16.5295](https://www.openstreetmap.org/?mlat=57.00337274&mlon=16.5295386852&zoom=13#map=13/57.0034/16.5295)
* Wikidata [change history](https://www.wikidata.org/w/index.php?title=Q106712174&type=revision&diff=1421180428&oldid=1421093321)

**Comment by salgo60** [comment]
* "[SE0930861000004814](https://badplatsen.havochvatten.se/badplatsen/karta/#/bath/SE0930861000004814) missing test location" -> "Gamla färjeläget Oknö , Mönsterås" denna https://github.com/salgo60/Svenskabadplatser/issues/33
* "[SE0110191000004834](https://badplatsen.havochvatten.se/badplatsen/karta/#/bath/SE0110191000004834) missing test location" -> "Munkholmsbadet , Sigtuna" https://github.com/salgo60/Svenskabadplatser/issues/34
* "[SE0241884000004954](https://badplatsen.havochvatten.se/badplatsen/karta/#/bath/SE0241884000004954) missing test location" -> "Uskavigården , Nora" https://github.com/salgo60/Svenskabadplatser/issues/32
