### ISSUE TITLE
ML det nya heta även för badvatten?

### ISSUE THREAD

**Issue by salgo60** [salgo60/Svenskabadplatser#58]
Allmän fundering eftersom allt nu skall vara data drivet och många tror att allt kan lösas med [ML](https://en.wikipedia.org/wiki/Machine_learning) , min tro/övertygelse är att ML utan bra [länkade data](https://5stardata.info/en/) inte blir så mycket. Googlar man badvatten hittar man [SVT undersökning](http://pejl.svt.se/badplatser-som-kan-vara-fororenade/) där dom kopplar ihop med andra datamängder

**Fråga**: vad ser ni som nästa steg, vilken typ av data map badvatten/miljömål/övervakning behöver ni etc....  några datamängder vi borde ha i Wikidata? skapar ni motsvarande [IT projekt gör med roadmaps](https://www.wikidata.org/wiki/Wikidata:Development_plan) om vad ni vill komma skall?

Tänker även på saker som detta ["Skyltar med ovanligt budskap"](https://www.havochvatten.se/arkiv/aktuellt/2021-05-17-skyltar-med-ovanligt-budskap.html) / [Miljömålsuppföljning](https://www.havochvatten.se/overvakning-och-uppfoljning/miljomalsuppfoljning.html)

![image](https://user-images.githubusercontent.com/14206509/118695091-14eb9080-b80d-11eb-88df-bc80b5c58de0.png)

**IoT** Södertälje kommun [sätter ut IoT](https://www.linkedin.com/posts/mathilda-moberg-3570301b5_changeahead-iot-smartcities-activity-6800285558858924032-7C0O) pratar ni med dom och uppmuntrar ni andra att springa åt detta håll?
* samordnas detta av er så vi enkelt kan hämta IoT data? eller vem tar denna bollen... 

![image](https://user-images.githubusercontent.com/14206509/118699547-f0de7e00-b811-11eb-801a-be15a3f276d9.png)

**Comment by anderselias** [comment]
Det borde gå att relativt enkelt skapa (öppna) analysverktyg utifrån data som tillgängliggörs i Havs- och vattenmyndighetens API, tänker t.ex. på klusteranalyser av föroreningskällor. Tror dock inte data sig behöver finnas i Wikidata, däremot måste de geografiska positionerna vara av god kvalitet och objekten länkade till rätt vatten (sjöar, vattendrag, kustvatten).

**Comment by salgo60** [comment]
Frågan är väl vilka saker exponeras i de olika datasetten och var saker knyts ihop....  att sitta och matcha vatten till varje nytt dataset som läggs in känns inte 2021 :sweat_drops: :dizzy_face:

Vore fantastiskt om allt badvattens data i EU har samma struktur och kopplingar till liknande källor så att en ML lösning för ett område enkelt kan tillämpas på annat gissar jag... kanske ha en databas med vilka dataset som pratar med varandra :heart_eyes:

**Comment by anderselias** [comment]
Mmmm, tror dock det här behöver synkas hos statistikansvarig myndighet. Kanske går att lägga till ett verktygsstöd så att sjö-id (el. dyl.) läggs till vid inventering/provtagning? Då har vi data med en koppling och på köpet en förvaltning/ägarskap av själva relationen. Men som sagt, det skulle krävas en dialog med och mellan inblandade myndigheter.

**Comment by salgo60** [comment]
Annan galen ide är det jag skrivit lite om på [github.com/salgo60/ArtportalenWikidata](https://github.com/salgo60/ArtportalenWikidata)

Är en app [Inaturalist ](https://www.inaturalist.org/home) som är enormt duktiga och har även en ML app [Seek](https://www.inaturalist.org/pages/seek_app)

* i Wikidata har vi dom Inaturalist kopplade bla. > 588 000 med [Property:P3151](https://www.wikidata.org/wiki/Property:P3151) iNaturalist taxon-ID
* idag används det till att om iNaturalist användaren har satt [licens på bilder](https://www.inaturalist.org/blog/48165-we-want-you-to-license-your-inaturalist-photos-before-april-15th) fria e.g. [CC-0](https://creativecommons.org/share-your-work/public-domain/cc0/) / [video](https://www.youtube.com/watch?v=zFnJJDTYbJs) och att den arten saknar bild i Wikidata (idag saknas ung. bild på 50 000 arter) så hämtar folk hem dom se video [del 1](https://www.youtube.com/watch?v=Wg1dCpyAgbU&list=PLNGVg5O3dJezq_cCq9mPUiGvfk-X1Rtc7&index=1) / [del 2](https://www.youtube.com/watch?v=zpHsHwR_kBc) 
* en egenskap [Property P7471](https://www.wikidata.org/wiki/Property_talk:P7471) **iNaturalist plats-ID** identifierar en yta i iNaturalist som man kan se observationer från

Min vaga tanke är att lägga upp ytor som badstränder, naturreservat i iNaturalist och hämta hem art/växt observationer -->  lite spännande "community research". 

Fördelen med iNaturalist är att man bifogar bild och att andra användare rankar upp en observation --> att man får högre trovärdighet se "[Using iNaturalist to Contribute your Nature observations to science](https://edis.ifas.ufl.edu/publication/uw458)"

**Comment by salgo60** [comment]
Inget "Intresse" för dialog hos Hav se [email](https://github.com/salgo60/Svenskabadplatser/blob/main/Email/Gmail%20-%20Vem%20hos%20er%20kan%20svara%20p%C3%A5%20anv%C3%A4ndadet%20av%20badvatten%20identifieraren%20-%20bathingWaterIdentifier%202.pdf) - **stänger denna**
