### ISSUE TITLE
SPARQL for finding distance bath water and connected water

### ISSUE THREAD

**Issue by salgo60** [salgo60/Svenskabadplatser#60]
The wish is something like this that shows a federated query of differencies between two domains
![image](https://user-images.githubusercontent.com/14206509/118703625-998edc80-b816-11eb-89a3-9b542e80a6c4.png)

* sparql 

Comment [Andrew Gray](https://mobile.twitter.com/generalising):

> 
> I worked one like this up for UK parliamentary constituencies - it was comparing the Wikidata geocoords with a federated SPARQL search 
> https://www.wikidata.org/wiki/Wikidata:WikiProject_British_Politicians/Sample_Queries#Federated_queries - second one listed here, "Querying Wikidata and recovering coordinates from Parliament Data"

**Comment by salgo60** [comment]
[SPARQL magic](https://query.wikidata.org/embed.html#%23defaultView%3AMap%7B%22hide%22%3A%5B%22%3Fbathcoord%22%2C%22%3Flakecoord%22%2C%22%3Fline%22%2C%22%3Fstr%22%2C%22%3Flayer%22%5D%7D%0ASELECT%20%3Fstr%20%3Fbathwater%20%3FbathwaterLabel%20%3Fbathcoord%20%3Flake%20%3FlakeLabel%20%3Flakecoord%20%3Fdist%20%3Fline%20%3FSJOID%20%3Flayer%20WHERE%20%7B%0A%20%20%3Fbathwater%20wdt%3AP6104%20wd%3AQ106774536.%0A%20%20%20%3Fbathwater%20%20wdt%3AP625%20%3Fxx.%0A%20%20%20%3Fbathwater%20%20p%3AP625%20%5B%20a%20wikibase%3ABestRank%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20psv%3AP625%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoLatitude%20%3Fbathcoordlat%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoLongitude%20%3Fbathcoordlon%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoGlobe%20%3Fglobe%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%5D%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20ps%3AP625%20%3Fbathcoord%0A%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20OPTIONAL%20%7B%20%3Fbathwater%20wdt%3AP605%20%3FNUTSID.%20%7D%0A%20%20%7B%0A%20%20%20%20%3Fbathwater%20wdt%3AP206%20%3Flake.%0A%20%20%20%3Flake%20%20wdt%3AP625%20%3Frr.%0A%20%20%20%20%20%20%20%3Flake%20%20p%3AP625%20%5Ba%20wikibase%3ABestRank%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20psv%3AP625%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoLatitude%20%3Flat%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoLongitude%20%3Flong%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoGlobe%20%3Fglobe2%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%5D%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20ps%3AP625%20%3Flakecoord%0A%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20OPTIONAL%20%7B%20%3Flake%20wdt%3AP761%20%3FSJOID.%20%7D%0A%20%20%7D%0A%20%20%20BIND%28geof%3Adistance%28%3Fbathcoord%2C%20%3Flakecoord%29%20as%20%3Fdist%29%20.%20%0A%20%20filter%20%28%3Fdist%20%3E%3D%203%29%0A%20%20BIND%20%28floor%28%3Fdist%2F10%29%2a10%20as%20%3Flayer%29%20%0A%20%20BIND%28CONCAT%28%27LINESTRING%20%28%27%2C%20STR%28%3Fbathcoordlon%29%2C%20%27%20%27%2C%20STR%28%3Fbathcoordlat%29%2C%20%27%2C%27%2C%20STR%28%3Flong%29%2C%20%27%20%27%2C%20STR%28%3Flat%29%2C%20%27%29%27%29%20AS%20%3Fstr%29%20.%0A%20%20BIND%28STRDT%28%3Fstr%2C%20geo%3AwktLiteral%29%20AS%20%3Fline%29%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22sv%2Cen%22.%20%7D%0A%7D%0AORDER%20BY%20DESC%28%3Fdist%29%0A)

Distans badplats koordinat sjö som badplatsen är kopplad till

![image](https://user-images.githubusercontent.com/14206509/118725924-dc5dae00-b830-11eb-91e7-17f135799664.png)

**Comment by anderselias** [comment]
Bra jobbat! Verkar ju som att SPARQL kan användas till "GIS-analyser". I HoV:s API så finns det koordinater både i badplatsens information (/feature) och i testLocationProfile. Jag vet inte hur datamodellen ser ut, kanske kan finnas flera testLocations per badplats (i alla fall teoretiskt). Tips HoV-myndigheten om verktyget :)

**Comment by salgo60** [comment]
Snyggt blev det vill testa att hämta Lantmäteriets data se om det kan ge oss en känsla av fel i grunddata med koordinaterna... har ingen bra taktik mer än manuellt slit att få mer sjöar kopplade plus är osäker hur ex. Mälaren skall kopplas.... där jag testade att koppla saker till Galten [Q5519368](https://www.wikidata.org/wiki/Special:WhatLinksHere/Q5519368) och andra direkt till Mälaren -  [sparql](https://query.wikidata.org/#%23defaultView%3AMap%7B%22hide%22%3A%5B%22%3Fbathcoord%22%2C%22%3Flakecoord%22%2C%22%3Fline%22%2C%22%3Fstr%22%2C%22%3Flayer%22%5D%7D%0ASELECT%20%3Fstr%20%3Fbathwater%20%3FbathwaterLabel%20%3Fbathcoord%20%3Flake%20%3FlakeLabel%20%3Flakecoord%20%3Fdist%20%3Fline%20%3FSJOID%20%3Flayer%20WHERE%20%7B%0A%20%20%3Fbathwater%20wdt%3AP6104%20wd%3AQ106774536.%0A%20%20%20%3Fbathwater%20%20wdt%3AP625%20%3Fxx.%0A%20%20%20%3Fbathwater%20%20p%3AP625%20%5B%20a%20wikibase%3ABestRank%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20psv%3AP625%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoLatitude%20%3Fbathcoordlat%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoLongitude%20%3Fbathcoordlon%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoGlobe%20%3Fglobe%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%5D%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20ps%3AP625%20%3Fbathcoord%0A%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20OPTIONAL%20%7B%20%3Fbathwater%20wdt%3AP605%20%3FNUTSID.%20%7D%0A%20%20%7B%0A%20%20%20%20%3Fbathwater%20wdt%3AP206%20%3Flake.%0A%20%20%20%3Flake%20%20wdt%3AP625%20%3Frr.%0A%20%20%20%20%20%20%20%3Flake%20%20p%3AP625%20%5Ba%20wikibase%3ABestRank%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20psv%3AP625%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoLatitude%20%3Flat%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoLongitude%20%3Flong%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoGlobe%20%3Fglobe2%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%5D%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20ps%3AP625%20%3Flakecoord%0A%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20OPTIONAL%20%7B%20%3Flake%20wdt%3AP761%20%3FSJOID.%20%7D%0A%20%20%7D%0A%20%20%20BIND%28geof%3Adistance%28%3Fbathcoord%2C%20%3Flakecoord%29%20as%20%3Fdist%29%20.%20%0A%20%20%23filter%20%28%3Fdist%20%3E%3D%203%29%0A%20%20BIND%20%28floor%28%3Fdist%2F10%29%2a10%20as%20%3Flayer%29%20%0A%20%20BIND%28CONCAT%28%27LINESTRING%20%28%27%2C%20STR%28%3Fbathcoordlon%29%2C%20%27%20%27%2C%20STR%28%3Fbathcoordlat%29%2C%20%27%2C%27%2C%20STR%28%3Flong%29%2C%20%27%20%27%2C%20STR%28%3Flat%29%2C%20%27%29%27%29%20AS%20%3Fstr%29%20.%0A%20%20BIND%28STRDT%28%3Fstr%2C%20geo%3AwktLiteral%29%20AS%20%3Fline%29%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22sv%2Cen%22.%20%7D%0A%7D%0AORDER%20BY%20DESC%28%3Fdist%29%0A)


![image](https://user-images.githubusercontent.com/14206509/118938609-21780200-b94f-11eb-91b3-9451f0746ce0.png)



Måste plugga lite nu har "[Overfitting and Generalization and Regularization - Machine Learning Course](https://www.youtube.com/watch?v=-zVe8upJMDU&list=PLS8J_PRPtGfdnPf9QqT7Itnn2rAHsoWqY&index=11)" kl: 13:00
