### ISSUE TITLE
Hur tänker VISS med sjöar som "består av" flera delar

### ISSUE THREAD

**Issue by salgo60** [salgo60/Svenskabadplatser#62]
Finns det en databas där relationer beskrivs så även vi noviser förstår? Vad rekommenderas i ett fall som nedan där WD och OSM verkar divergera

* se även [Wikipedia:Projekt Sveriges sjöar](https://sv.wikipedia.org/wiki/Wikipedia:Projekt_Sveriges_sj%C3%B6ar)
  * [Wikipedia:Projekt Grensidor Svenska insjöar](https://sv.wikipedia.org/wiki/Wikipedia:Projekt_Grensidor_Svenska_insj%C3%B6ar)
  * [Wikipedia:Projekt Sveriges sjöar/Fel och brister](https://sv.wikipedia.org/wiki/Wikipedia:Projekt_Sveriges_sj%C3%B6ar/Fel_och_brister) - intressant här är hur felrapporteras sjöar och till vem jmf https://github.com/salgo60/Svenskabadplatser/issues/56
      * **OBS** denna sida var [mest aktiv 2014/2015](https://sv.wikipedia.org/w/index.php?title=Wikipedia:Projekt_Sveriges_sj%C3%B6ar/Fel_och_brister&action=history) status idag okänd

* sv:wikipedia [Kustvattenförekomst](https://sv.wikipedia.org/wiki/Kustvattenf%C3%B6rekomst)

Exempel "mismatch WIkidata <-> OSM"
* Västra Öresjön 
  * WD [Q18196304](https://www.wikidata.org/wiki/Q18196304) 
  * WD har Sjö id [637072-130923](https://viss.lansstyrelsen.se/Waters.aspx?waterEUID=SE637072-130923) **OK VISS**

* Kalven 
  * WD [Q18196104](https://www.wikidata.org/wiki/Q18196104) 
  * WD har Sjö id [637541-131102](https://viss.lansstyrelsen.se/Waters.aspx?waterEUID=SE637541-131102)  **OK VISS**
![image](https://user-images.githubusercontent.com/14206509/118748927-de3d6680-b85c-11eb-91f4-b278bee94b5f.png)
* Östra Öresjön 
  * WD [Q18196321](https://www.wikidata.org/wiki/Q18196321)
  * WD har Sjö id [ [637523-131260](https://viss.lansstyrelsen.se/Waters.aspx?waterMSCD=WA31737230)

* Öresjön OSM : [relation/4040694](https://www.openstreetmap.org/relation/4040694#map=12/57.4301/12.6401)

* samma i verktyg [osm.wikidata.link](https://alpha.osm.wikidata.link/map/12/57.41893/12.64257?item=Q29571614)

**Comment by dpriskorn** [comment]
Spännande! Jag har förslag till lösning. Nytt WD objekt Öresjön som har delarna Östra,Västra Öresjön samt Kalven. Detta objekt kan sedan länkas med OSM-relationen. WDYT?

**Comment by dpriskorn** [comment]
Det är också möjligt att dela upp OSM relationen i 3 bitar enligt kommunes indelning, men det är jag inte säker på att OSM gemenskapen går med på för det strider mot 1 sak 1 objekt vilket är en grundbult i projektet.

**Comment by salgo60** [comment]
* VISS för Runn signalerar ett objekt
* Wikidata [Q1146737](https://www.wikidata.org/wiki/Q1146737)
  * VISS [SE670563-148814](https://viss.lansstyrelsen.se/Waters.aspx?waterEUID=SE670563-148814)
  
  
![image](https://user-images.githubusercontent.com/14206509/118778203-23c45880-b88a-11eb-8f1c-f2b71add4442.png)

**Comment by dpriskorn** [comment]
Jag skulle säga att det här är en bugg i VISS. Inconsistent data. Det är ju inget problem så länge man har en silo, men när vi ska länka ihop bliver det problem...

**Comment by salgo60** [comment]
Vi kan nog hantera det hela i WIkidata men vore intressant att höra hur Havs-och vattenmyndigheten tänker och hur dom vill beskriva saker i sitt API....

**Comment by salgo60** [comment]
Inget "Intresse" för dialog hos Hav se [email](https://github.com/salgo60/Svenskabadplatser/blob/main/Email/Gmail%20-%20Vem%20hos%20er%20kan%20svara%20p%C3%A5%20anv%C3%A4ndadet%20av%20badvatten%20identifieraren%20-%20bathingWaterIdentifier%202.pdf) - **stänger denna**

**Comment by dpriskorn** [comment]
Hmm.

**Comment by salgo60** [comment]
@dpriskorn är lite skillnad 
* Hav svar efter påstötning 3 veckor senare ingen av frågorna besvaras 
* EEA [svara efter 60 minuter](https://github.com/salgo60/EuropeanBathingWater/blob/main/Email/Gmail%20-%20Eionet%20bathingWaterIdentifier%20_-_%20Wikidata_Wikipedia.pdf) perfekt och [pekar på annat dokument](https://upload.wikimedia.org/wikipedia/commons/7/7f/WFD_data_for_Wikidata_%E2%80%93_final_report.pdf) "WFD data for Wikidata" som i princip gjort samma "Wikidata resa" som jag vill göra med badvatten men dom gjorde det med vatten

**Comment by dpriskorn** [comment]
Och svaret kom in från EEA runt 18, efter kontorstid! :)

**Comment by salgo60** [comment]
@dpriskorn japp men hon sitter i Danmark på [Kongens Nytorv 8](https://www.google.com/maps/place/Kongens+Nytorv+8,+1050+K%C3%B8benhavn,+Denmark/@55.6811522,12.5862413,3a,75y,160.07h,90.37t/data=!3m6!1e1!3m4!1sIYnZWSd7QZtQISXZyWASBg!2e0!7i16384!8i8192!4m5!3m4!1s0x465253183dbf2367:0x850b3ff065681d6c!8m2!3d55.6813628!4d12.5864357) satt väl och vänta på att springa ned till [Noma](https://www.youtube.com/watch?v=RPy41Sie8Os) tar bara [20 minuter](https://www.google.com/maps/dir/Kongens+Nytorv+8,+1050+K%C3%B8benhavn,+Denmark/Refshalevej+96,+1432+Copenhagen+Municipality,+K%C3%B8benhavn+K,+Denmark/@55.6829983,12.5896384,15z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x465253183dbf2367:0x850b3ff065681d6c!2m2!1d12.5864357!2d55.6813628!1m5!1m1!1s0x4652532ed8289525:0xa66d02fe69fb3ffc!2m2!1d12.6104669!2d55.6827859!3e2)  ;-)

**Comment by salgo60** [comment]
hade ett snack med Hav [Magnus Petzäll](https://www.linkedin.com/in/magnuspetzall/?locale=sv_SE) och känns som fokus är [EU inspire](https://inspire.ec.europa.eu/) där jag gissar att en av slutpodukterna är tydliga termer med tydligt ägande. Att vara mer synliga då det gäller GITHUB öppen data verkar inte finnas på dagordningen och badvatten är inte top prio

* alltid spännande med öppna communities
* annan intressant tanke är att IoT för att mäta badvatten kanske är oldschool då det finns stellit data som Copernicus se [iot-device-wikibase/issues/5](https://github.com/salgo60/iot-device-wikibase/issues/5)
