### ISSUE TITLE
Städa upp datakvalitet koordinater badplatser

### ISSUE THREAD

**Issue by salgo60** [salgo60/Svenskabadplatser#64]
**Fråga Havs- och vattenmyndigheten:** Har ni tittat på att städa upp era koordinater med andra källor? Vad har ni testat och vad fungerar? 

**Kontakta kommuner direkt** 
Jag har via facebook tagit kontakt med några kommuner men
1) ofta inget svar
1) jag skickar med länk till Issues på GITHUB men nu tycker Facebooks ML algoritm att jag inte får posta länkar (se bild nedan) så FB känns som ett omoget sätt att kommunicera. Vi har tidigare försökt "driva in" data från kommuner om Vindskydd etc. [länk](http://minancestry.blogspot.com/2020/06/vindskydd-i-sverige.html) men dom flesta förstår inte ens vad Öppen Data är. I några större kommuner som Uppsala får man data men känns som hjulet uppfinns varje gång och man är inte vana att jobba agilt. Finns några som sticker ut som [Umeå](https://opendata.umea.se/pages/startsida/), [Södertälje](https://www.sodertalje.se/kommun-och-politik/for-medborgare/oppna-data/), [Gävle](https://www.gavle.se/kommunens-service/kommun-och-politik/statistik-fakta-och-oppna-data/oppna-data/) men inga som har plattformar att logga fel/diskutera... ett [anti-pattern](https://en.wikipedia.org/wiki/Anti-pattern) jag ser mer och mer är glada tillrop på Linked in med likes... att likt Wikidata använda en extern publik prioriterad backlog - [backlog WD](https://phabricator.wikimedia.org/tag/Wikidata) / [senaste ändringar](https://phabricator.wikimedia.org/project/profile/71/) / gratis [programvaran Phabricator](https://www.mediawiki.org/wiki/Phabricator/sv) / att [jobba agilt](https://blog.crisp.se/2012/10/25/henrikkniberg/agile-product-ownership-in-a-nutshell)

![image](https://user-images.githubusercontent.com/14206509/118768219-08a01b80-b87f-11eb-8bc5-52eb005b198c.png)

**Fråga:**
Er erfarenhet av kompetens/ kvalitet på datakällor / APIer / enkelhet kommunicera med för att städa data
1) Kommuner
1) Öppna communities som Wikidata / OSM
1) Lantmäteriet se https://github.com/salgo60/Svenskabadplatser/issues/63#issuecomment-843747571

**Comment by salgo60** [comment]
Pratade kort med "Havs- och vattenmyndigheten" Stina och om koordinater och indelning av bad görs av kommunerna
* "Havs- och vattenmyndighetens" blir glada om dom får bad som även inte är EU bad rapporterade till sig
* skillnad på NUTSkod och bathingwaterindicator kunde inte redogöras för blir email senare
* fel koordinater då får man leta reda på personen som är ansvarig skall finnas i APIet
* i [VISS finns](https://viss.lansstyrelsen.se/) finns sjöid och t.ex. Mälaren kan vara uppdelad på > 10 olika delar
* vid provtagning så är punkten för provtagning beroende av strömmar etc,... kan vara att 2 närliggande bad behöver olika mätpunkter förstår jag
* inrapportering av Bad till EU sker i december

**Comment by anderselias** [comment]
Ok, det låter som att ni har en bra dialog! Tyvärr är det bara 40 % av "test locations" som har en epost-adress angiven under responsibleAuthority. En del har angivit personnamn, och inte en funktionsbrevlåda, vilket kan försvåra kontakt. Känns spontant som att de här bristerna skulle kunna avhjälpas med tydligare instruktioner kring hur formulären fylls i, men jag vet inget om hur de ser ut idag.

**Comment by salgo60** [comment]
du är för snabb det ovan är en kladd .... visade sig att min telefon funka utan att jag tänkte på det mitt nummer verkar vara 0735152902

**Comment by salgo60** [comment]
Inget "Intresse" för dialog hos Hav se [email](https://github.com/salgo60/Svenskabadplatser/blob/main/Email/Gmail%20-%20Vem%20hos%20er%20kan%20svara%20p%C3%A5%20anv%C3%A4ndadet%20av%20badvatten%20identifieraren%20-%20bathingWaterIdentifier%202.pdf) - **stänger denna**
